services:
  
  backend:
    container_name: simple_blog_backend
    # image: thepujon/simple_blog_backend:1.5
    build:
      context: ./
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://${DATABASE_USER:-dandu}:${DATABASE_PASSWORD:-dandu123}@mysql:3306/${DATABASE_NAME:-gandu}
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ${DATABASE_NAME:-gandu}
      DATABASE_USER: ${DATABASE_USER:-dandu}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-dandu123}
      NODE_ENV: ${NODE_ENV}


      REDIS_HOST: redis-stack
      REDIS_PORT: 6379
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM}

      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
    depends_on:
      mysql:
        condition: service_healthy
      redis-stack:
        condition: service_healthy
    networks:
      - app_network
