import { Job as PrismaJob, Prisma } from '@prisma/client';
import { JobEntity } from '../../../domain/entities/job.entity';

/**
 * Job Mapper — Bidirectional mapping between Prisma model and Domain entity.
 *
 * Why a separate mapper?
 * → The domain entity must never know about Prisma types.
 * → If we switch from Prisma to another ORM, only this file changes.
 * → Centralizes all type conversions (e.g., Prisma Decimal → number).
 */
export class JobMapper {
  /**
   * Map a Prisma Job model to a Domain JobEntity.
   */
  static toDomain(prismaJob: PrismaJob): JobEntity {
    return new JobEntity(
      prismaJob.id,
      prismaJob.authId,
      // Company
      prismaJob.company,
      prismaJob.companyUrl,
      prismaJob.companyLinkedin,
      prismaJob.companyFacebook,
      prismaJob.companyTwitter,
      prismaJob.companyLogo,
      // Role
      prismaJob.role,
      prismaJob.location,
      prismaJob.locationType,
      // Salary
      prismaJob.salaryDisplay,
      prismaJob.salaryMin,
      prismaJob.salaryMax,
      prismaJob.salaryCurrency,
      // Contact
      prismaJob.contactPerson,
      prismaJob.contactEmail,
      prismaJob.contactPhone,
      // Application
      prismaJob.appliedDate,
      prismaJob.appliedVia,
      prismaJob.jobPostingUrl,
      prismaJob.status,
      prismaJob.responseStatus,
      prismaJob.responseDate,
      // Details
      prismaJob.techStack,
      prismaJob.jobDescription,
      prismaJob.requirements,
      prismaJob.responsibilities,
      prismaJob.benefits,
      // Interview
      prismaJob.interviewScheduled,
      prismaJob.interviewDate,
      prismaJob.interviewType,
      prismaJob.interviewRound,
      prismaJob.interviewLocation,
      prismaJob.interviewNotes,
      // Organization
      prismaJob.priority,
      prismaJob.tags,
      prismaJob.isFavorite,
      prismaJob.isArchived,
      // Offer — offerAmount is now Float in MongoDB (was Decimal)
      prismaJob.offerAmount,
      prismaJob.offerDate,
      prismaJob.offerDeadline,
      prismaJob.offerNotes,
      // Rejection
      prismaJob.rejectionReason,
      prismaJob.rejectionDate,
      // Notes
      prismaJob.notes,
      // AI
      prismaJob.aiParsedData as Record<string, unknown> | null,
      prismaJob.aiConfidenceScore,
      prismaJob.sourceType,
      prismaJob.rawJobPosting,
      // Follow-up
      prismaJob.nextFollowUpDate,
      prismaJob.followUpCount,
      prismaJob.lastFollowUpDate,
      // Timestamps
      prismaJob.createdAt,
      prismaJob.updatedAt,
      prismaJob.deletedAt,
    );
  }

  /**
   * Map a Domain JobEntity to Prisma create input.
   * Used when creating a new job (id is auto-generated by MongoDB).
   */
  static toCreateInput(entity: JobEntity): Prisma.JobCreateInput {
    return {
      authUser: { connect: { id: entity.authId } },
      company: entity.company,
      companyUrl: entity.companyUrl,
      companyLinkedin: entity.companyLinkedin,
      companyFacebook: entity.companyFacebook,
      companyTwitter: entity.companyTwitter,
      companyLogo: entity.companyLogo,
      role: entity.role,
      location: entity.location,
      locationType: entity.locationType,
      salaryDisplay: entity.salaryDisplay,
      salaryMin: entity.salaryMin,
      salaryMax: entity.salaryMax,
      salaryCurrency: entity.salaryCurrency,
      contactPerson: entity.contactPerson,
      contactEmail: entity.contactEmail,
      contactPhone: entity.contactPhone,
      appliedDate: entity.appliedDate,
      appliedVia: entity.appliedVia,
      jobPostingUrl: entity.jobPostingUrl,
      status: entity.status,
      responseStatus: entity.responseStatus,
      responseDate: entity.responseDate,
      techStack: entity.techStack,
      jobDescription: entity.jobDescription,
      requirements: entity.requirements,
      responsibilities: entity.responsibilities,
      benefits: entity.benefits,
      interviewScheduled: entity.interviewScheduled,
      interviewDate: entity.interviewDate,
      interviewType: entity.interviewType,
      interviewRound: entity.interviewRound,
      interviewLocation: entity.interviewLocation,
      interviewNotes: entity.interviewNotes,
      priority: entity.priority,
      tags: entity.tags,
      isFavorite: entity.isFavorite,
      isArchived: entity.isArchived,
      offerAmount: entity.offerAmount,
      offerDate: entity.offerDate,
      offerDeadline: entity.offerDeadline,
      offerNotes: entity.offerNotes,
      rejectionReason: entity.rejectionReason,
      rejectionDate: entity.rejectionDate,
      notes: entity.notes,
      aiParsedData: entity.aiParsedData as Prisma.InputJsonValue | undefined,
      aiConfidenceScore: entity.aiConfidenceScore,
      sourceType: entity.sourceType,
      rawJobPosting: entity.rawJobPosting,
      nextFollowUpDate: entity.nextFollowUpDate,
      followUpCount: entity.followUpCount,
      lastFollowUpDate: entity.lastFollowUpDate,
    };
  }

  /**
   * Map a Domain JobEntity to Prisma update input.
   * Only includes fields that have been set (non-undefined).
   */
  static toUpdateInput(entity: JobEntity): Prisma.JobUpdateInput {
    return {
      company: entity.company,
      companyUrl: entity.companyUrl,
      companyLinkedin: entity.companyLinkedin,
      companyFacebook: entity.companyFacebook,
      companyTwitter: entity.companyTwitter,
      companyLogo: entity.companyLogo,
      role: entity.role,
      location: entity.location,
      locationType: entity.locationType,
      salaryDisplay: entity.salaryDisplay,
      salaryMin: entity.salaryMin,
      salaryMax: entity.salaryMax,
      salaryCurrency: entity.salaryCurrency,
      contactPerson: entity.contactPerson,
      contactEmail: entity.contactEmail,
      contactPhone: entity.contactPhone,
      appliedDate: entity.appliedDate,
      appliedVia: entity.appliedVia,
      jobPostingUrl: entity.jobPostingUrl,
      status: entity.status,
      responseStatus: entity.responseStatus,
      responseDate: entity.responseDate,
      techStack: entity.techStack,
      jobDescription: entity.jobDescription,
      requirements: entity.requirements,
      responsibilities: entity.responsibilities,
      benefits: entity.benefits,
      interviewScheduled: entity.interviewScheduled,
      interviewDate: entity.interviewDate,
      interviewType: entity.interviewType,
      interviewRound: entity.interviewRound,
      interviewLocation: entity.interviewLocation,
      interviewNotes: entity.interviewNotes,
      priority: entity.priority,
      tags: entity.tags,
      isFavorite: entity.isFavorite,
      isArchived: entity.isArchived,
      offerAmount: entity.offerAmount,
      offerDate: entity.offerDate,
      offerDeadline: entity.offerDeadline,
      offerNotes: entity.offerNotes,
      rejectionReason: entity.rejectionReason,
      rejectionDate: entity.rejectionDate,
      notes: entity.notes,
      aiParsedData: entity.aiParsedData as Prisma.InputJsonValue | undefined,
      aiConfidenceScore: entity.aiConfidenceScore,
      sourceType: entity.sourceType,
      rawJobPosting: entity.rawJobPosting,
      nextFollowUpDate: entity.nextFollowUpDate,
      followUpCount: entity.followUpCount,
      lastFollowUpDate: entity.lastFollowUpDate,
      deletedAt: entity.deletedAt,
    };
  }
}
